AWSTemplateFormatVersion: "2010-09-09"
Description: "🕵️‍♀️🕵️‍♀️🕵️‍♀️ CloudFormation使ってみる！"

Resources:
  # S3バケット
  S3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    Properties:
      BucketName: !Sub "${AWS::StackName}-s3-bucket"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-s3-bucket"
